#!/usr/bin/env bash

echo "Start.."

echo "Running Linters..."
cd apps/gym && pnpm run lint || exit 1

echo "🧪 Running Tests..."
pnpm test || exit 1

echo "Building..."
pnpm run build || exit 1

echo "go back ?!.."
cd -

echo "second project.."
cd apps/brand-site && pnpm run lint || exit 1

echo "🧪 Running Tests..."
pnpm test || exit 1

echo "Building..."
pnpm run build || exit 1

echo "All checks passed! Proceeding with push."
